database:
  url: "postgresql://postgres:3110@localhost:5432/hh_etl"

hh_api:
  text: "СБЕР"
  area: 1
  search_field: "company_name"
  items_on_page: 20

telegram:
  token: "token"
  chat_id: "chat_id"

storage:
  parquet_path: "./data/"
  compression: "snappy"
